version: '3.2'

services:
  db:
    image: postgres:13.2-alpine
    container_name: 'todo_db'
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    
  web:
    build: .
    container_name: 'todo_app'
    ports:
      - "80:5000"
    working_dir: '/tmp/work'
    volumes:
      - ./todo_app:/tmp/work
    depends_on:
      - db
    stdin_open: True
    tty: True

